[default_config]
version = "0.10.0"
assembler = "gas"
instruction_set = "x86-64"

[default_config.opts]
compiler = "gcc"
compile_flags_txt = ["-static"]
diagnostics = true
default_diagnostics = false
